name: Plugin upload
description: Organizes the plugin files in the correct structure and uploads it as an artifact
author: mauer

inputs:
  pluginName:
    description: "Name of the plugin"
    required: true
  archFolder:
    description: "Subfolder in which the library will be placed in"
    required: true
  xplFileName:
    description: "Path to the xpl plugin file"
    required: true

runs:
  using: "composite"
  steps:
    - name: Prepare Deployment Structure
      shell: bash
      run: |
        mkdir -p "deploy-${{ inputs.pluginName }}/${{ inputs.pluginName }}/${{ inputs.archFolder }}"
        mv "${{ inputs.xplFileName }}" "deploy-${{ inputs.pluginName }}/${{ inputs.pluginName }}/${{ inputs.archFolder }}"

    - name: Upload the plugin
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.pluginName }}-${{ env.platform }}
        path: deploy-${{ inputs.pluginName }}/*
        if-no-files-found: error
