name: Make package
description: Create an installation package for the plugin
author: mauer

inputs:
  pluginName:
    description: "Name of the plugin"
    required: true

runs:
  using: "composite"
  steps:
    - name: Copy required files into deployment path
      shell: bash
      run: |
        mkdir -p "deploy-${{ inputs.pluginName }}/${{ inputs.pluginName }}
        cp -r ./resources/examples "deploy-${{ inputs.pluginName }}/${{ inputs.pluginName }}"
        cp -r ./resources/templates "deploy-${{ inputs.pluginName }}/${{ inputs.pluginName }}"
        cp ./docs/changelog.md "deploy-${{ inputs.pluginName }}/${{ inputs.pluginName }}"
        cp ./docs/README-md "deploy-${{ inputs.pluginName }}/${{ inputs.pluginName }}"
        cp ./LICENSE "deploy-${{ inputs.pluginName }}/${{ inputs.pluginName }}"

    - name: Upload the plugin
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.pluginName }}
        path: deploy-${{ inputs.pluginName }}/*
        if-no-files-found: error
